apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydemo
  labels:
    app: mydemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydemo
  template:
    metadata:
      labels:
        app: mydemo
    spec:
      containers:
      - image: demo
        name: mydemo
