apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- deployment.yaml
- service.yaml

images:
 - name: demo
   newName: lfbear/gitops-test
   newTag: "37431d4"
