apiVersion: v1
kind: Service
metadata:
  name: mydemo
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: mydemo
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 80
