apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mydemo
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./"
  prune: true
  timeout: 1m
  images:
  - name: demo
    newName: lfbear/gitops-test
    newTag: "5897b18"
